/**
 * Site content.
 *
 * The restaurants and their signature dishes are real. Ratings, review counts,
 * prices, delivery times and the customer testimonials are illustrative sample
 * data invented for this demo — see the note in the footer.
 *
 * Dish photography is hotlinked from Wikimedia Commons; each item carries the
 * author and licence its licence requires us to display, surfaced by the
 * "Photo credits" panel in the footer. `js/render.js` falls back to the local
 * category image if a remote photo ever stops resolving.
 *
 * Generated content — see the roster in the project history rather than editing
 * image URLs by hand.
 */

export const CITIES = ['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai'];

export const CATEGORIES = [
  { id: 'pizza',        name: 'Pizza',        img: 'images/pizza.png' },
  { id: 'broast',       name: 'Broast',       img: 'images/broast.png' },
  { id: 'chicken',      name: 'Chicken',      img: 'images/chicken.jpg' },
  { id: 'burgers',      name: 'Burgers',      img: 'images/burger.jpg' },
  { id: 'shakes',       name: 'Shakes',       img: 'images/shakes.jpg' },
  { id: 'sandwiches',   name: 'Sandwiches',   img: 'images/sandwich.jpg' },
  { id: 'pasta',        name: 'Pasta',        img: 'images/pasta.jpg' },
  { id: 'desserts',     name: 'Desserts',     img: 'images/dessert.jpg' },
];

/** Local category art, doubling as the fallback when a remote photo fails. */
export const CATEGORY_IMG = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.img]));

export const RESTAURANTS = [
  {
    id: 'truffles',
    name: 'Truffles',
    area: 'Koramangala',
    city: 'Bangalore',
    rating: 4.6,
    reviews: 18420,
    eta: 30,
    deliveryFee: 0,
    priceForTwo: 700,
    signature: 'Ultimate Chicken Cheese Burger',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Cheeseburger_with_onions_at_Hatfield_Heath_Festival_2017.jpg/500px-Cheeseburger_with_onions_at_Hatfield_Heath_Festival_2017.jpg',
    credit: { author: 'Acabashi', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Cheeseburger_with_onions_at_Hatfield_Heath_Festival_2017.jpg' },
    cuisines: ['burgers', 'sandwiches', 'shakes', 'pasta'],
    menu: [
      {
        id: 'truffles-ultimate-chicken-cheese-burger',
        name: 'Ultimate Chicken Cheese Burger',
        price: 359,
        category: 'burgers',
        veg: false,
        desc: 'The one it is famous for — crumb-fried chicken, molten cheese',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Argentine_chicken_burger_sandwiches_with_lettuce%2C_tomato%2C_fried_egg%2C_and_mozzarella_cheese_on_Don_Yeyo_buns.jpg/500px-Argentine_chicken_burger_sandwiches_with_lettuce%2C_tomato%2C_fried_egg%2C_and_mozzarella_cheese_on_Don_Yeyo_buns.jpg',
        credit: { author: 'Horacio Cambeiro', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Argentine_chicken_burger_sandwiches_with_lettuce,_tomato,_fried_egg,_and_mozzarella_cheese_on_Don_Yeyo_buns.jpg' },
      },
      {
        id: 'truffles-paneer-tikka-burger',
        name: 'Paneer Tikka Burger',
        price: 289,
        category: 'burgers',
        veg: true,
        desc: 'Char-grilled paneer, mint mayo',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Panir_Tikka_Indian_cheese_grilled.jpg/500px-Panir_Tikka_Indian_cheese_grilled.jpg',
        credit: { author: 'Sonja Pauen -Stanhopea', license: 'CC BY 2.0 de', page: 'https://commons.wikimedia.org/wiki/File:Panir_Tikka_Indian_cheese_grilled.jpg' },
      },
      {
        id: 'truffles-chicken-club-sandwich',
        name: 'Chicken Club Sandwich',
        price: 279,
        category: 'sandwiches',
        veg: false,
        desc: 'Triple decker with egg and bacon',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Club-sandwich.jpg/500px-Club-sandwich.jpg',
        credit: { author: 'Memm', license: 'CC BY 3.0', page: 'https://commons.wikimedia.org/wiki/File:Club-sandwich.jpg' },
      },
      {
        id: 'truffles-death-by-chocolate-shake',
        name: 'Death by Chocolate Shake',
        price: 229,
        category: 'shakes',
        veg: true,
        desc: 'Thick chocolate shake, brownie chunks',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Chocolate_milkshake_..._%F0%9F%98%8B.jpg/500px-Chocolate_milkshake_..._%F0%9F%98%8B.jpg',
        credit: { author: 'Bernard DUPONT', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chocolate_milkshake_..._%F0%9F%98%8B.jpg' },
      },
      {
        id: 'truffles-penne-alfredo',
        name: 'Penne Alfredo',
        price: 319,
        category: 'pasta',
        veg: true,
        desc: 'Creamy parmesan sauce',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Fetuccine_Alfredo.jpg/500px-Fetuccine_Alfredo.jpg',
        credit: { author: 'Jorgehdezalonso', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Fetuccine_Alfredo.jpg' },
      },
    ],
  },
  {
    id: 'corner-house',
    name: 'Corner House Ice Cream',
    area: 'Residency Road',
    city: 'Bangalore',
    rating: 4.7,
    reviews: 22150,
    eta: 25,
    deliveryFee: 0,
    priceForTwo: 400,
    signature: 'Death by Chocolate',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Strawberry_Ice_Cream_Sundae_%2826853326784%29.jpg/500px-Strawberry_Ice_Cream_Sundae_%2826853326784%29.jpg',
    credit: { author: 'Sam Howzit', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Strawberry_Ice_Cream_Sundae_(26853326784).jpg' },
    cuisines: ['desserts', 'shakes'],
    menu: [
      {
        id: 'corner-house-death-by-chocolate',
        name: 'Death by Chocolate',
        price: 289,
        category: 'desserts',
        veg: true,
        desc: 'Bangalore\'s most ordered sundae — brownie, ice cream, hot fudge',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Ben_and_Jerry%27s_Hot_Fudge_Sundae_%2819384608984%29.jpg/500px-Ben_and_Jerry%27s_Hot_Fudge_Sundae_%2819384608984%29.jpg',
        credit: { author: 'Willis Lam', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Ben_and_Jerry%27s_Hot_Fudge_Sundae_(19384608984).jpg' },
      },
      {
        id: 'corner-house-hot-chocolate-fudge',
        name: 'Hot Chocolate Fudge',
        price: 259,
        category: 'desserts',
        veg: true,
        desc: 'Vanilla scoops drowned in warm fudge',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Tony%27s_Cable_Car_Restaurant_Hot_Fudge_Sundae_%2828440589022%29.jpg/500px-Tony%27s_Cable_Car_Restaurant_Hot_Fudge_Sundae_%2828440589022%29.jpg',
        credit: { author: 'Willis Lam', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Tony%27s_Cable_Car_Restaurant_Hot_Fudge_Sundae_(28440589022).jpg' },
      },
      {
        id: 'corner-house-caramel-crunch-sundae',
        name: 'Caramel Crunch Sundae',
        price: 249,
        category: 'desserts',
        veg: true,
        desc: 'Butterscotch, praline, whipped cream',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Gold_Digger_-Sundae_with_salted_caramel_and_-chocolate_ice_cream_drizzled_with_-butterscotch_and_hot_-fudge._From_Hans%27_Homemade_Ice_Cream_at_the_Anaheim_Packing_House._-icecream_-dessert_-foodporn_-nofilter_%2814658377071%29.jpg/500px-thumbnail.jpg',
        credit: { author: 'Drew Hubbard,  Ben Waters', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Gold_Digger_-Sundae_with_salted_caramel_and_-chocolate_ice_cream_drizzled_with_-butterscotch_and_hot_-fudge._From_Hans%27_Homemade_Ice_Cream_at_the_Anaheim_Packing_House._-icecream_-dessert_-foodporn_-nofilter_(14658377071).jpg' },
      },
      {
        id: 'corner-house-cold-coffee-shake',
        name: 'Cold Coffee Shake',
        price: 189,
        category: 'shakes',
        veg: true,
        desc: 'Thick, blended cold coffee',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Frapp%C3%A9.jpg/500px-Frapp%C3%A9.jpg',
        credit: { author: 'Kritzolina', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Frapp%C3%A9.jpg' },
      },
    ],
  },
  {
    id: 'meghana-foods',
    name: 'Meghana Foods',
    area: 'Residency Road',
    city: 'Bangalore',
    rating: 4.5,
    reviews: 41300,
    eta: 35,
    deliveryFee: 0,
    priceForTwo: 800,
    signature: 'Boneless Chicken Biryani',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg/500px-A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg',
    credit: { author: 'Subhrajyoti07', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:A_home_made_plate_of_mutton_biryani_served_with_chicken_kassa_cooked_in_the_bengali_style.jpg' },
    cuisines: ['chicken'],
    menu: [
      {
        id: 'meghana-foods-boneless-chicken-biryani',
        name: 'Boneless Chicken Biryani',
        price: 420,
        category: 'chicken',
        veg: false,
        desc: 'The Andhra biryani the queues are for',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Chicken_Biryani_combo.jpg/500px-Chicken_Biryani_combo.jpg',
        credit: { author: 'Rajeeb (Marajozkee)', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_Biryani_combo.jpg' },
      },
      {
        id: 'meghana-foods-chicken-65',
        name: 'Chicken 65',
        price: 320,
        category: 'chicken',
        veg: false,
        desc: 'Deep-fried, curry leaf and chilli',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Chicken_65_%28Dish%29.jpg/500px-Chicken_65_%28Dish%29.jpg',
        credit: { author: 'Amiyashrivastava', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_65_(Dish).jpg' },
      },
      {
        id: 'meghana-foods-andhra-chicken-fry',
        name: 'Andhra Chicken Fry',
        price: 349,
        category: 'chicken',
        veg: false,
        desc: 'Dry roast, heavy on the pepper',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Andhra_Fried_Chicken.JPG/500px-Andhra_Fried_Chicken.JPG',
        credit: { author: 'Aditya525125', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Andhra_Fried_Chicken.JPG' },
      },
      {
        id: 'meghana-foods-chicken-kebab',
        name: 'Chicken Kebab',
        price: 299,
        category: 'chicken',
        veg: false,
        desc: 'Charcoal grilled, boneless',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Chicken_Tikka_Kebab.jpg/500px-Chicken_Tikka_Kebab.jpg',
        credit: { author: 'Sumit Surai', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_Tikka_Kebab.jpg' },
      },
    ],
  },
  {
    id: 'toit',
    name: 'Toit Brewpub',
    area: 'Indiranagar',
    city: 'Bangalore',
    rating: 4.6,
    reviews: 15980,
    eta: 40,
    deliveryFee: 49,
    priceForTwo: 1600,
    signature: 'Wood-fired Pizza',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Wood-fired_Pizza_Oven_at_Baronessa_Italian_Restaurant.jpg/500px-Wood-fired_Pizza_Oven_at_Baronessa_Italian_Restaurant.jpg',
    credit: { author: 'Zacatillo1', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Wood-fired_Pizza_Oven_at_Baronessa_Italian_Restaurant.jpg' },
    cuisines: ['pizza', 'burgers'],
    menu: [
      {
        id: 'toit-margherita-pizza',
        name: 'Margherita Pizza',
        price: 425,
        category: 'pizza',
        veg: true,
        desc: 'Wood-fired, San Marzano and fior di latte',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Margherita_Originale.JPG/500px-Margherita_Originale.JPG',
        credit: { author: 'Mario56', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG' },
      },
      {
        id: 'toit-pepperoni-pizza',
        name: 'Pepperoni Pizza',
        price: 545,
        category: 'pizza',
        veg: false,
        desc: 'Double pepperoni, thin crust',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Pizza_Tradici%C3%B3n_Napolitana.jpg/500px-Pizza_Tradici%C3%B3n_Napolitana.jpg',
        credit: { author: 'Rjcastillo', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Pizza_Tradici%C3%B3n_Napolitana.jpg' },
      },
      {
        id: 'toit-toit-chicken-burger',
        name: 'Toit Chicken Burger',
        price: 465,
        category: 'burgers',
        veg: false,
        desc: 'Grilled chicken, brewhouse sauce',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Sloppy_Chicken_Burgers.jpg/500px-Sloppy_Chicken_Burgers.jpg',
        credit: { author: 'bjacobdawson', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Sloppy_Chicken_Burgers.jpg' },
      },
    ],
  },
  {
    id: 'koshys',
    name: 'Koshy\'s',
    area: 'St Mark\'s Road',
    city: 'Bangalore',
    rating: 4.3,
    reviews: 9840,
    eta: 35,
    deliveryFee: 39,
    priceForTwo: 600,
    signature: 'Club Sandwich',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/City_Centre_Club_Sandwich_for_room_service_at_Holiday_Inn_Qingdao_City_Centre_%2820191004082448%29.jpg/500px-City_Centre_Club_Sandwich_for_room_service_at_Holiday_Inn_Qingdao_City_Centre_%2820191004082448%29.jpg',
    credit: { author: 'N509FZ', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:City_Centre_Club_Sandwich_for_room_service_at_Holiday_Inn_Qingdao_City_Centre_(20191004082448).jpg' },
    cuisines: ['sandwiches', 'chicken'],
    menu: [
      {
        id: 'koshys-club-sandwich',
        name: 'Club Sandwich',
        price: 249,
        category: 'sandwiches',
        veg: false,
        desc: 'An eighty-year-old recipe, unchanged',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Club_Sandwich_Toast_and_Tea.jpg/500px-Club_Sandwich_Toast_and_Tea.jpg',
        credit: { author: 'Mayejiro', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Club_Sandwich_Toast_and_Tea.jpg' },
      },
      {
        id: 'koshys-chicken-cutlet',
        name: 'Chicken Cutlet',
        price: 219,
        category: 'chicken',
        veg: false,
        desc: 'Crumb fried, served with mustard',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Chicken_cutlets.jpg/500px-Chicken_cutlets.jpg',
        credit: { author: 'nayeli @ nyam.ru', license: 'CC BY 3.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_cutlets.jpg' },
      },
      {
        id: 'koshys-cheese-toast',
        name: 'Cheese Toast',
        price: 179,
        category: 'sandwiches',
        veg: true,
        desc: 'Thick-cut toast, grilled cheddar',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cheese_on_toast-11.jpg/500px-Cheese_on_toast-11.jpg',
        credit: { author: 'jules', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Cheese_on_toast-11.jpg' },
      },
    ],
  },
  {
    id: 'bademiya',
    name: 'Bademiya',
    area: 'Colaba',
    city: 'Mumbai',
    rating: 4.4,
    reviews: 27600,
    eta: 30,
    deliveryFee: 0,
    priceForTwo: 600,
    signature: 'Seekh Kebab Roll',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Seekh_Kebab.JPG/500px-Seekh_Kebab.JPG',
    credit: { author: 'raasiel', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Seekh_Kebab.JPG' },
    cuisines: ['chicken', 'sandwiches'],
    menu: [
      {
        id: 'bademiya-chicken-seekh-kebab-roll',
        name: 'Chicken Seekh Kebab Roll',
        price: 260,
        category: 'chicken',
        veg: false,
        desc: 'The midnight Colaba institution',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Kebab_roll_-_chaiiwala_2024-02-10.jpg/500px-Kebab_roll_-_chaiiwala_2024-02-10.jpg',
        credit: { author: 'Andy Li', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Kebab_roll_-_chaiiwala_2024-02-10.jpg' },
      },
      {
        id: 'bademiya-chicken-tikka-roll',
        name: 'Chicken Tikka Roll',
        price: 280,
        category: 'chicken',
        veg: false,
        desc: 'Charcoal tikka wrapped in roomali',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chicken-kathi-roll-recipe.jpg/500px-Chicken-kathi-roll-recipe.jpg',
        credit: { author: 'Vivekpat30', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken-kathi-roll-recipe.jpg' },
      },
      {
        id: 'bademiya-baida-roti',
        name: 'Baida Roti',
        price: 240,
        category: 'sandwiches',
        veg: false,
        desc: 'Egg-fried minced chicken parcel',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Chicken_baida_roti.jpg/500px-Chicken_baida_roti.jpg',
        credit: { author: 'MaharajaMandy', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_baida_roti.jpg' },
      },
      {
        id: 'bademiya-chicken-bhuna-roll',
        name: 'Chicken Bhuna Roll',
        price: 290,
        category: 'chicken',
        veg: false,
        desc: 'Slow-bhuna masala, thick roomali',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Chicken_Kathi_Roll_%285646735923%29.jpg/500px-Chicken_Kathi_Roll_%285646735923%29.jpg',
        credit: { author: 'Andy Mitchell from Glasgow, UK', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_Kathi_Roll_(5646735923).jpg' },
      },
    ],
  },
  {
    id: 'amar-juice',
    name: 'Amar Juice Centre',
    area: 'Vile Parle West',
    city: 'Mumbai',
    rating: 4.4,
    reviews: 13270,
    eta: 25,
    deliveryFee: 0,
    priceForTwo: 350,
    signature: 'Mumbaiya Grilled Sandwich',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Bombay_cheese_sandwich.jpg/500px-Bombay_cheese_sandwich.jpg',
    credit: { author: 'Wind Hashira', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Bombay_cheese_sandwich.jpg' },
    cuisines: ['sandwiches', 'shakes'],
    menu: [
      {
        id: 'amar-juice-grilled-veg-cheese-sandwich',
        name: 'Grilled Veg Cheese Sandwich',
        price: 180,
        category: 'sandwiches',
        veg: true,
        desc: 'Potato, cucumber, chutney, a lot of cheese',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Grilled_cheese_sandwich.jpg/500px-Grilled_cheese_sandwich.jpg',
        credit: { author: 'Maggie Hoffman', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Grilled_cheese_sandwich.jpg' },
      },
      {
        id: 'amar-juice-bombay-masala-toast',
        name: 'Bombay Masala Toast',
        price: 150,
        category: 'sandwiches',
        veg: true,
        desc: 'Green chutney and chaat masala',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Bombay_Sandwich.jpg/500px-Bombay_Sandwich.jpg',
        credit: { author: 'Princejain17', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Bombay_Sandwich.jpg' },
      },
      {
        id: 'amar-juice-pav-bhaji',
        name: 'Pav Bhaji',
        price: 190,
        category: 'sandwiches',
        veg: true,
        desc: 'Butter-soaked pav, award-winning bhaji',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Bhaji_pav_2.jpg/500px-Bhaji_pav_2.jpg',
        credit: { author: 'BHAAGIi', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Bhaji_pav_2.jpg' },
      },
      {
        id: 'amar-juice-chocolate-milkshake',
        name: 'Chocolate Milkshake',
        price: 170,
        category: 'shakes',
        veg: true,
        desc: 'Their most ordered shake',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Chocolate_milkshake%2C_Good_Stuff_Eatery.jpg/500px-Chocolate_milkshake%2C_Good_Stuff_Eatery.jpg',
        credit: { author: 'Ser Amantio di Nicolao', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chocolate_milkshake,_Good_Stuff_Eatery.jpg' },
      },
      {
        id: 'amar-juice-alphonso-mango-shake',
        name: 'Alphonso Mango Shake',
        price: 190,
        category: 'shakes',
        veg: true,
        desc: 'Summer bestseller, seasonal pulp',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Mango_milkshake.jpg/500px-Mango_milkshake.jpg',
        credit: { author: 'Swathi sri srinivasa raghavan', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Mango_milkshake.jpg' },
      },
    ],
  },
  {
    id: 'pizza-by-the-bay',
    name: 'Pizza By The Bay',
    area: 'Marine Drive',
    city: 'Mumbai',
    rating: 4.3,
    reviews: 11420,
    eta: 40,
    deliveryFee: 49,
    priceForTwo: 1800,
    signature: 'Quattro Formaggi',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Piante_Margherita_Pizza_Slice.jpg/500px-Piante_Margherita_Pizza_Slice.jpg',
    credit: { author: 'Aspensmonster', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Piante_Margherita_Pizza_Slice.jpg' },
    cuisines: ['pizza', 'pasta', 'desserts'],
    menu: [
      {
        id: 'pizza-by-the-bay-quattro-formaggi-pizza',
        name: 'Quattro Formaggi Pizza',
        price: 649,
        category: 'pizza',
        veg: true,
        desc: 'Four cheeses, sea-facing since 1995',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg/500px-Pizza_quattro_formaggi_at_restaurant%2C_Chalk_Farm_Road%2C_London.jpg',
        credit: { author: 'Ewan Munro from London, UK', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Pizza_quattro_formaggi_at_restaurant,_Chalk_Farm_Road,_London.jpg' },
      },
      {
        id: 'pizza-by-the-bay-chicken-tikka-pizza',
        name: 'Chicken Tikka Pizza',
        price: 699,
        category: 'pizza',
        veg: false,
        desc: 'Tandoori chicken, red onion',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Chicken_Pizza_1.jpg/500px-Chicken_Pizza_1.jpg',
        credit: { author: 'Gaurav Dhwaj Khadka', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_Pizza_1.jpg' },
      },
      {
        id: 'pizza-by-the-bay-spaghetti-bolognese',
        name: 'Spaghetti Bolognese',
        price: 589,
        category: 'pasta',
        veg: false,
        desc: 'Slow-cooked ragu',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Spaghetti_Bolognese_-_Figaros%2C_Brighton_2023-10-06.jpg/500px-Spaghetti_Bolognese_-_Figaros%2C_Brighton_2023-10-06.jpg',
        credit: { author: 'Andy Li', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Spaghetti_Bolognese_-_Figaros,_Brighton_2023-10-06.jpg' },
      },
      {
        id: 'pizza-by-the-bay-penne-arrabbiata',
        name: 'Penne Arrabbiata',
        price: 519,
        category: 'pasta',
        veg: true,
        desc: 'Chilli, garlic, fresh tomato',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Penne_Arrabbiata.jpg/500px-Penne_Arrabbiata.jpg',
        credit: { author: 'Petar Milošević', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Penne_Arrabbiata.jpg' },
      },
      {
        id: 'pizza-by-the-bay-sizzling-brownie',
        name: 'Sizzling Brownie',
        price: 389,
        category: 'desserts',
        veg: true,
        desc: 'Brownie, ice cream, hot chocolate',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ice_creams.jpg/500px-Ice_creams.jpg',
        credit: { author: 'Tsaenmai', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Ice_creams.jpg' },
      },
    ],
  },
  {
    id: 'theobroma',
    name: 'Theobroma',
    area: 'Colaba',
    city: 'Mumbai',
    rating: 4.6,
    reviews: 19800,
    eta: 30,
    deliveryFee: 0,
    priceForTwo: 500,
    signature: 'Chocolate Brownie',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Chocolate-brownie-hachatw.jpg/500px-Chocolate-brownie-hachatw.jpg',
    credit: { author: 'JefferySAC', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chocolate-brownie-hachatw.jpg' },
    cuisines: ['desserts', 'sandwiches'],
    menu: [
      {
        id: 'theobroma-classic-chocolate-brownie',
        name: 'Classic Chocolate Brownie',
        price: 165,
        category: 'desserts',
        veg: true,
        desc: 'The brownie that built the bakery',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Brownie_IMG_001.jpg/500px-Brownie_IMG_001.jpg',
        credit: { author: 'Phadke09', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Brownie_IMG_001.jpg' },
      },
      {
        id: 'theobroma-dutch-truffle-cake',
        name: 'Dutch Truffle Cake',
        price: 295,
        category: 'desserts',
        veg: true,
        desc: 'Dense chocolate ganache',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Chocolate_truffle_cake.jpg/500px-Chocolate_truffle_cake.jpg',
        credit: { author: 'Sanika Dhumal', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chocolate_truffle_cake.jpg' },
      },
      {
        id: 'theobroma-red-velvet-cupcake',
        name: 'Red Velvet Cupcake',
        price: 175,
        category: 'desserts',
        veg: true,
        desc: 'Cream cheese frosting',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Delicious_Red_Velvet_Cupcake.jpg/500px-Delicious_Red_Velvet_Cupcake.jpg',
        credit: { author: 'Renter2000', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Delicious_Red_Velvet_Cupcake.jpg' },
      },
      {
        id: 'theobroma-chicken-croissant-sandwich',
        name: 'Chicken Croissant Sandwich',
        price: 285,
        category: 'sandwiches',
        veg: false,
        desc: 'All-butter croissant, roast chicken',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Croissant_sandwich_set_lunch.jpg/500px-Croissant_sandwich_set_lunch.jpg',
        credit: { author: 'Geoffreyrabbit', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Croissant_sandwich_set_lunch.jpg' },
      },
    ],
  },
  {
    id: 'k-rustom',
    name: 'K. Rustom & Co.',
    area: 'Churchgate',
    city: 'Mumbai',
    rating: 4.5,
    reviews: 8600,
    eta: 25,
    deliveryFee: 29,
    priceForTwo: 250,
    signature: 'Ice Cream Sandwich',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Chipwich_ice_cream_sandwich.jpg/500px-Chipwich_ice_cream_sandwich.jpg',
    credit: { author: 'Crave Better Foods, LLC, copyright owner of The Original Chi', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chipwich_ice_cream_sandwich.jpg' },
    cuisines: ['desserts'],
    menu: [
      {
        id: 'k-rustom-ice-cream-sandwich',
        name: 'Ice Cream Sandwich',
        price: 120,
        category: 'desserts',
        veg: true,
        desc: 'Wafer-pressed slab, since 1953',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/It%27s_It_ice_cream_sandwich_2021-07.png/500px-It%27s_It_ice_cream_sandwich_2021-07.png',
        credit: { author: 'WhatamIdoing', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:It%27s_It_ice_cream_sandwich_2021-07.png' },
      },
      {
        id: 'k-rustom-roasted-almond-crunch',
        name: 'Roasted Almond Crunch',
        price: 140,
        category: 'desserts',
        veg: true,
        desc: 'Their most asked-for flavour',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Almond_Raisin_Ice_Cream.jpg/500px-Almond_Raisin_Ice_Cream.jpg',
        credit: { author: 'Manjeshwari poet mysore', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Almond_Raisin_Ice_Cream.jpg' },
      },
      {
        id: 'k-rustom-kesar-pista-ice-cream',
        name: 'Kesar Pista Ice Cream',
        price: 140,
        category: 'desserts',
        veg: true,
        desc: 'Saffron and pistachio',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Pistachio_ice_cream_with_whipped_mascarpone_and_pistachio_biscotti.jpg/500px-Pistachio_ice_cream_with_whipped_mascarpone_and_pistachio_biscotti.jpg',
        credit: { author: 'Arnold Gatilao', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Pistachio_ice_cream_with_whipped_mascarpone_and_pistachio_biscotti.jpg' },
      },
    ],
  },
  {
    id: 'karims',
    name: 'Karim\'s',
    area: 'Jama Masjid',
    city: 'Delhi',
    rating: 4.4,
    reviews: 31500,
    eta: 40,
    deliveryFee: 0,
    priceForTwo: 700,
    signature: 'Mutton Burra',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Kebab_platter.JPG/500px-Kebab_platter.JPG',
    credit: { author: 'Deboli Dutta', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Kebab_platter.JPG' },
    cuisines: ['chicken'],
    menu: [
      {
        id: 'karims-mutton-burra-kebab',
        name: 'Mutton Burra Kebab',
        price: 480,
        category: 'chicken',
        veg: false,
        desc: 'Charcoal-seared, the Jama Masjid classic',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Grilled_lamb_chops.jpg/500px-Grilled_lamb_chops.jpg',
        credit: { author: 'Fumikas Sagisavas', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Grilled_lamb_chops.jpg' },
      },
      {
        id: 'karims-chicken-jahangiri',
        name: 'Chicken Jahangiri',
        price: 420,
        category: 'chicken',
        veg: false,
        desc: 'Rich almond and cream gravy',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Mughlai_food.JPG/500px-Mughlai_food.JPG',
        credit: { author: 'SwingingUvula', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Mughlai_food.JPG' },
      },
      {
        id: 'karims-mutton-seekh-kebab',
        name: 'Mutton Seekh Kebab',
        price: 390,
        category: 'chicken',
        veg: false,
        desc: 'Hand-minced, skewer-grilled',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Indian_Chicken_Seekh_Kebab.jpg/500px-Indian_Chicken_Seekh_Kebab.jpg',
        credit: { author: 'Ishitadsa', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Indian_Chicken_Seekh_Kebab.jpg' },
      },
      {
        id: 'karims-chicken-tandoori-half',
        name: 'Chicken Tandoori (Half)',
        price: 360,
        category: 'chicken',
        veg: false,
        desc: 'Clay oven, overnight marinade',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Tandoori_chicken_Indian.jpg/500px-Tandoori_chicken_Indian.jpg',
        credit: { author: 'pelican', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Tandoori_chicken_Indian.jpg' },
      },
    ],
  },
  {
    id: 'moti-mahal',
    name: 'Moti Mahal',
    area: 'Daryaganj',
    city: 'Delhi',
    rating: 4.2,
    reviews: 16900,
    eta: 35,
    deliveryFee: 39,
    priceForTwo: 900,
    signature: 'Butter Chicken',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Chicken_makhani.jpg/500px-Chicken_makhani.jpg',
    credit: { author: 'stu_spivack', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg' },
    cuisines: ['chicken'],
    menu: [
      {
        id: 'moti-mahal-butter-chicken',
        name: 'Butter Chicken',
        price: 520,
        category: 'chicken',
        veg: false,
        desc: 'Invented in this kitchen in the 1950s',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Butter_Chicken%2C_Lamb_Rogan_Josh%2C_Saag_Paneer_-_Bollywood_2_Go%2C_QV_Food_Court_Medium_Thali_AUD8.90_%282554594775%29.jpg/500px-Butter_Chicken%2C_Lamb_Rogan_Josh%2C_Saag_Paneer_-_Bollywood_2_Go%2C_QV_Food_Court_Medium_Thali_AUD8.90_%282554594775%29.jpg',
        credit: { author: 'Alpha from Melbourne, Australia', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Butter_Chicken,_Lamb_Rogan_Josh,_Saag_Paneer_-_Bollywood_2_Go,_QV_Food_Court_Medium_Thali_AUD8.90_(2554594775).jpg' },
      },
      {
        id: 'moti-mahal-chicken-tikka',
        name: 'Chicken Tikka',
        price: 420,
        category: 'chicken',
        veg: false,
        desc: 'The original tandoori tikka',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Chicken_tikka_in_Araku_Valley%2C_Andhra_Pradesh_01.jpg/500px-Chicken_tikka_in_Araku_Valley%2C_Andhra_Pradesh_01.jpg',
        credit: { author: 'Satdeep Gill', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_tikka_in_Araku_Valley,_Andhra_Pradesh_01.jpg' },
      },
      {
        id: 'moti-mahal-malai-chicken-tikka',
        name: 'Malai Chicken Tikka',
        price: 450,
        category: 'chicken',
        veg: false,
        desc: 'Cream and cheese marinade',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Malai_chicken_tikka.JPG/500px-Malai_chicken_tikka.JPG',
        credit: { author: 'Nithyasrm', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Malai_chicken_tikka.JPG' },
      },
      {
        id: 'moti-mahal-tandoori-chicken-full',
        name: 'Tandoori Chicken (Full)',
        price: 620,
        category: 'chicken',
        veg: false,
        desc: 'Whole bird, clay oven',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Grilled_Tandoori_chicken.jpg/500px-Grilled_Tandoori_chicken.jpg',
        credit: { author: 'Rajeeb Dutta', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Grilled_Tandoori_chicken.jpg' },
      },
    ],
  },
  {
    id: 'wengers',
    name: 'Wenger\'s',
    area: 'Connaught Place',
    city: 'Delhi',
    rating: 4.4,
    reviews: 7300,
    eta: 30,
    deliveryFee: 39,
    priceForTwo: 400,
    signature: 'Black Forest Pastry',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Black_Forest_gateau.jpg/500px-Black_Forest_gateau.jpg',
    credit: { author: 'Mikelo', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Black_Forest_gateau.jpg' },
    cuisines: ['desserts', 'sandwiches'],
    menu: [
      {
        id: 'wengers-black-forest-pastry',
        name: 'Black Forest Pastry',
        price: 150,
        category: 'desserts',
        veg: true,
        desc: 'A Connaught Place counter since 1926',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Black_Forest_cake_4.jpg/500px-Black_Forest_cake_4.jpg',
        credit: { author: 'Roozitaa', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Black_Forest_cake_4.jpg' },
      },
      {
        id: 'wengers-chicken-patty',
        name: 'Chicken Patty',
        price: 90,
        category: 'sandwiches',
        veg: false,
        desc: 'Flaky puff, peppery filling',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Yank_Sing_Chicken_Curry_Puff_Pastry_%2815271515224%29.jpg/500px-Yank_Sing_Chicken_Curry_Puff_Pastry_%2815271515224%29.jpg',
        credit: { author: 'Willis Lam', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Yank_Sing_Chicken_Curry_Puff_Pastry_(15271515224).jpg' },
      },
      {
        id: 'wengers-plum-cake',
        name: 'Plum Cake',
        price: 320,
        category: 'desserts',
        veg: true,
        desc: 'Rum-soaked fruit, sold by the loaf',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Slice_of_Christmas_cake_%2811879724696%29.jpg/500px-Slice_of_Christmas_cake_%2811879724696%29.jpg',
        credit: { author: 'James Petts from London, England', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Slice_of_Christmas_cake_(11879724696).jpg' },
      },
      {
        id: 'wengers-pineapple-pastry',
        name: 'Pineapple Pastry',
        price: 140,
        category: 'desserts',
        veg: true,
        desc: 'Sponge, cream, glazed pineapple',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Pineapple_Pastry.JPG/500px-Pineapple_Pastry.JPG',
        credit: { author: 'Mk2010', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Pineapple_Pastry.JPG' },
      },
    ],
  },
  {
    id: 'burger-singh',
    name: 'Burger Singh',
    area: 'Rajouri Garden',
    city: 'Delhi',
    rating: 4.1,
    reviews: 12400,
    eta: 30,
    deliveryFee: 29,
    priceForTwo: 450,
    signature: 'Amritsari Murg Burger',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Chicken_Caesar_Burger_-_Leon_2024-10-27.jpg/500px-Chicken_Caesar_Burger_-_Leon_2024-10-27.jpg',
    credit: { author: 'Andy Li', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_Caesar_Burger_-_Leon_2024-10-27.jpg' },
    cuisines: ['burgers', 'shakes'],
    menu: [
      {
        id: 'burger-singh-amritsari-murg-burger',
        name: 'Amritsari Murg Burger',
        price: 229,
        category: 'burgers',
        veg: false,
        desc: 'Punjabi-spiced chicken patty',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Fried_chicken_burger_.jpg/500px-Fried_chicken_burger_.jpg',
        credit: { author: 'Kurt Kaiser', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Fried_chicken_burger_.jpg' },
      },
      {
        id: 'burger-singh-up-wale-panditji-burger',
        name: 'UP Wale Panditji Burger',
        price: 189,
        category: 'burgers',
        veg: true,
        desc: 'Spiced potato and paneer',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Fancy_Veggie_Burger_and_Fries_-_Joe%27s_Burger_House_2024-07-07.jpg/500px-Fancy_Veggie_Burger_and_Fries_-_Joe%27s_Burger_House_2024-07-07.jpg',
        credit: { author: 'Andy Li', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Fancy_Veggie_Burger_and_Fries_-_Joe%27s_Burger_House_2024-07-07.jpg' },
      },
      {
        id: 'burger-singh-chicken-tikka-burger',
        name: 'Chicken Tikka Burger',
        price: 239,
        category: 'burgers',
        veg: false,
        desc: 'Tandoori patty, mint mayo',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Grilled_Chicken_Burger%2C_D%C3%B4me_Byford%2C_2026_%2801%29.jpg/500px-Grilled_Chicken_Burger%2C_D%C3%B4me_Byford%2C_2026_%2801%29.jpg',
        credit: { author: 'Bahnfrend', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Grilled_Chicken_Burger,_D%C3%B4me_Byford,_2026_(01).jpg' },
      },
      {
        id: 'burger-singh-thick-chocolate-shake',
        name: 'Thick Chocolate Shake',
        price: 159,
        category: 'shakes',
        veg: true,
        desc: 'Blended with brownie',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Chocolate_milkshake.jpg/500px-Chocolate_milkshake.jpg',
        credit: { author: 'Hegde Neha', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chocolate_milkshake.jpg' },
      },
    ],
  },
  {
    id: 'olive-bar',
    name: 'Olive Bar & Kitchen',
    area: 'Mehrauli',
    city: 'Delhi',
    rating: 4.5,
    reviews: 6200,
    eta: 45,
    deliveryFee: 79,
    priceForTwo: 3500,
    signature: 'Truffle Ravioli',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Liat_Portal_for_Foodie_Disorder_-_Ravioli_with_mushrooms_and_spinach_in_cream_sauce.jpg/500px-Liat_Portal_for_Foodie_Disorder_-_Ravioli_with_mushrooms_and_spinach_in_cream_sauce.jpg',
    credit: { author: 'HaJunkiyada', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Ravioli_with_mushrooms_and_spinach_in_cream_sauce.jpg' },
    cuisines: ['pasta', 'pizza', 'desserts'],
    menu: [
      {
        id: 'olive-bar-wild-mushroom-ravioli',
        name: 'Wild Mushroom Ravioli',
        price: 890,
        category: 'pasta',
        veg: true,
        desc: 'Hand-folded, truffle butter',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ravioli_di_Faraona.JPG/500px-Ravioli_di_Faraona.JPG',
        credit: { author: 'OneArmedMan', license: 'Public domain', page: 'https://commons.wikimedia.org/wiki/File:Ravioli_di_Faraona.JPG' },
      },
      {
        id: 'olive-bar-spaghetti-aglio-e-olio',
        name: 'Spaghetti Aglio e Olio',
        price: 720,
        category: 'pasta',
        veg: true,
        desc: 'Garlic, chilli, good olive oil',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Spaghetti_aglio_e_olio_KB.jpg/500px-Spaghetti_aglio_e_olio_KB.jpg',
        credit: { author: 'Bairuilong', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Spaghetti_aglio_e_olio_KB.jpg' },
      },
      {
        id: 'olive-bar-lasagne-al-forno',
        name: 'Lasagne al Forno',
        price: 850,
        category: 'pasta',
        veg: false,
        desc: 'Layered ragu and bechamel',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Meaty_Lasagna_8of8_%288736299782%29.jpg/500px-Meaty_Lasagna_8of8_%288736299782%29.jpg',
        credit: { author: 'Breville USA', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:Meaty_Lasagna_8of8_(8736299782).jpg' },
      },
      {
        id: 'olive-bar-tiramisu',
        name: 'Tiramisu',
        price: 480,
        category: 'desserts',
        veg: true,
        desc: 'Mascarpone, espresso, cocoa',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Dolce_Tiramis%C3%B9_monoporzione.jpg/500px-Dolce_Tiramis%C3%B9_monoporzione.jpg',
        credit: { author: 'Anna.Massini', license: 'CC BY 4.0', page: 'https://commons.wikimedia.org/wiki/File:Dolce_Tiramis%C3%B9_monoporzione.jpg' },
      },
    ],
  },
  {
    id: 'buhari',
    name: 'Buhari Hotel',
    area: 'Anna Salai',
    city: 'Chennai',
    rating: 4.2,
    reviews: 14800,
    eta: 30,
    deliveryFee: 0,
    priceForTwo: 500,
    signature: 'Chicken 65',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kolkata_mutton_biryani.jpg/500px-Kolkata_mutton_biryani.jpg',
    credit: { author: 'DeepanjanGhosh', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Kolkata_mutton_biryani.jpg' },
    cuisines: ['chicken'],
    menu: [
      {
        id: 'buhari-chicken-65',
        name: 'Chicken 65',
        price: 280,
        category: 'chicken',
        veg: false,
        desc: 'Invented here in 1965',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Chicken_65_2.jpg/500px-Chicken_65_2.jpg',
        credit: { author: 'Gaurav Dhwaj Khadka', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Chicken_65_2.jpg' },
      },
      {
        id: 'buhari-buhari-chicken-biryani',
        name: 'Buhari Chicken Biryani',
        price: 340,
        category: 'chicken',
        veg: false,
        desc: 'Seeraga samba rice, Chennai style',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Shrimp_Biriyani.JPG/500px-Shrimp_Biriyani.JPG',
        credit: { author: 'Jyothis', license: 'CC BY-SA 3.0', page: 'https://commons.wikimedia.org/wiki/File:Shrimp_Biriyani.JPG' },
      },
      {
        id: 'buhari-grilled-chicken',
        name: 'Grilled Chicken',
        price: 390,
        category: 'chicken',
        veg: false,
        desc: 'Half bird, charcoal grilled',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Roast_Chicken_Hot_Plate.jpg/500px-Roast_Chicken_Hot_Plate.jpg',
        credit: { author: 'safaritravelplus', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Roast_Chicken_Hot_Plate.jpg' },
      },
      {
        id: 'buhari-chicken-kothu-parotta',
        name: 'Chicken Kothu Parotta',
        price: 260,
        category: 'chicken',
        veg: false,
        desc: 'Shredded parotta, minced chicken',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Kotthu_s_piletinom.JPG/500px-Kotthu_s_piletinom.JPG',
        credit: { author: 'Wikimedia Commons', license: 'Public domain', page: 'https://commons.wikimedia.org/wiki/File:Kotthu_s_piletinom.JPG' },
      },
    ],
  },
  {
    id: 'broast-factory',
    name: 'The Broast Factory',
    area: 'Banjara Hills',
    city: 'Hyderabad',
    rating: 4.3,
    reviews: 5400,
    eta: 30,
    deliveryFee: 0,
    priceForTwo: 600,
    signature: 'Classic Chicken Broast',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fried-Chicken-Set.jpg/500px-Fried-Chicken-Set.jpg',
    credit: { author: 'Evan-Amos', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Fried-Chicken-Set.jpg' },
    cuisines: ['broast', 'burgers'],
    menu: [
      {
        id: 'broast-factory-classic-chicken-broast-4-pc',
        name: 'Classic Chicken Broast (4 pc)',
        price: 379,
        category: 'broast',
        veg: false,
        desc: 'Pressure-fried, crackling crust',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Tavuk_%28pirzola%29.jpg/500px-Tavuk_%28pirzola%29.jpg',
        credit: { author: 'E4024', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Tavuk_(pirzola).jpg' },
      },
      {
        id: 'broast-factory-peri-peri-broast-8-pc',
        name: 'Peri Peri Broast (8 pc)',
        price: 679,
        category: 'broast',
        veg: false,
        desc: 'Dusted in peri peri',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Fried_chicken_pieces_coated_in_sauce_with_sesame_seeds_2025.jpg/500px-Fried_chicken_pieces_coated_in_sauce_with_sesame_seeds_2025.jpg',
        credit: { author: 'Faisal Ahammad', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Fried_chicken_pieces_coated_in_sauce_with_sesame_seeds_2025.jpg' },
      },
      {
        id: 'broast-factory-broast-bucket-12-pc',
        name: 'Broast Bucket (12 pc)',
        price: 999,
        category: 'broast',
        veg: false,
        desc: 'Family pack with two dips',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Fried_Chicken_%28Unsplash%29.jpg/500px-Fried_Chicken_%28Unsplash%29.jpg',
        credit: { author: 'Brian Chan tigerrulezzz', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Fried_Chicken_(Unsplash).jpg' },
      },
      {
        id: 'broast-factory-crispy-chicken-burger',
        name: 'Crispy Chicken Burger',
        price: 259,
        category: 'burgers',
        veg: false,
        desc: 'Broast fillet in a bun',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Chargrilled_Chicken_Burger_-_Leon.jpg/500px-Chargrilled_Chicken_Burger_-_Leon.jpg',
        credit: { author: 'Andy Li', license: 'CC0', page: 'https://commons.wikimedia.org/wiki/File:Chargrilled_Chicken_Burger_-_Leon.jpg' },
      },
    ],
  },
  {
    id: 'broast-nation',
    name: 'Broast Nation',
    area: 'Tolichowki',
    city: 'Hyderabad',
    rating: 4.1,
    reviews: 3900,
    eta: 35,
    deliveryFee: 29,
    priceForTwo: 500,
    signature: 'Signature Broast',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Fried_chicken_legs%2C_Rostov-on-Don%2C_Russia.jpg/500px-Fried_chicken_legs%2C_Rostov-on-Don%2C_Russia.jpg',
    credit: { author: 'Vyacheslav Argenberg', license: 'CC BY 4.0', page: 'https://commons.wikimedia.org/wiki/File:Fried_chicken_legs,_Rostov-on-Don,_Russia.jpg' },
    cuisines: ['broast', 'chicken'],
    menu: [
      {
        id: 'broast-nation-signature-broast-chicken',
        name: 'Signature Broast Chicken',
        price: 349,
        category: 'broast',
        veg: false,
        desc: 'House spice blend, 24-hour brine',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Roast_Chicken.jpg/500px-Roast_Chicken.jpg',
        credit: { author: 'Gaurav Dhwaj Khadka', license: 'CC BY-SA 4.0', page: 'https://commons.wikimedia.org/wiki/File:Roast_Chicken.jpg' },
      },
      {
        id: 'broast-nation-spicy-broast-wings',
        name: 'Spicy Broast Wings',
        price: 289,
        category: 'broast',
        veg: false,
        desc: 'Eight wings, hot glaze',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Buffalo_Burgers_Buffalo_Chicken_Wings_%2836082467922%29.jpg/500px-Buffalo_Burgers_Buffalo_Chicken_Wings_%2836082467922%29.jpg',
        credit: { author: 'Willis Lam', license: 'CC BY-SA 2.0', page: 'https://commons.wikimedia.org/wiki/File:Buffalo_Burgers_Buffalo_Chicken_Wings_(36082467922).jpg' },
      },
      {
        id: 'broast-nation-chicken-popcorn',
        name: 'Chicken Popcorn',
        price: 199,
        category: 'chicken',
        veg: false,
        desc: 'Bite-sized, ranch dip',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/O%27Cup_Popcorn_Chicken_%289071196321%29.jpg/500px-O%27Cup_Popcorn_Chicken_%289071196321%29.jpg',
        credit: { author: 'Elsie Hui', license: 'CC BY 2.0', page: 'https://commons.wikimedia.org/wiki/File:O%27Cup_Popcorn_Chicken_(9071196321).jpg' },
      },
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Ananya Rao',
    role: 'Product Designer, Bangalore',
    rating: 5,
    text: 'I order from Crunch at least three times a week. The live tracking is accurate to the minute and the food has never once shown up cold.',
  },
  {
    name: 'Rahul Mehta',
    role: 'Software Engineer, Mumbai',
    rating: 5,
    text: 'The search actually understands what I want. I typed the name of a dish rather than a restaurant and it found exactly the right place.',
  },
  {
    name: 'Priya Nair',
    role: 'Architect, Chennai',
    rating: 4,
    text: 'Great curation of local institutions rather than only the big chains. Found three neighbourhood places I now order from constantly.',
  },
  {
    name: 'Vikram Singh',
    role: 'Founder, Delhi',
    rating: 5,
    text: 'Free delivery on most of my regular spots and it remembers my last order. Checkout takes about ten seconds.',
  },
];

/** Menu items flattened once, each tagged with its restaurant — used by search. */
export const ALL_DISHES = RESTAURANTS.flatMap((r) =>
  r.menu.map((m) => ({ ...m, restaurantId: r.id, restaurantName: r.name }))
);

export const getRestaurant = (id) => RESTAURANTS.find((r) => r.id === id) || null;

export const getDish = (id) => ALL_DISHES.find((d) => d.id === id) || null;

/** Live count per category, so the cards never advertise a stale number. */
export function categoryCounts() {
  const counts = new Map(CATEGORIES.map((c) => [c.id, 0]));
  for (const d of ALL_DISHES) {
    if (counts.has(d.category)) counts.set(d.category, counts.get(d.category) + 1);
  }
  return counts;
}

/** Photo attribution, deduplicated by source file — required by the licences. */
export const IMAGE_CREDITS = (() => {
  const seen = new Map();
  const add = (label, c) => {
    if (c?.page && !seen.has(c.page)) seen.set(c.page, { label, ...c });
  };
  for (const r of RESTAURANTS) {
    add(r.name, r.credit);
    for (const d of r.menu) add(d.name, d.credit);
  }
  return [...seen.values()].sort((a, b) => a.label.localeCompare(b.label));
})();
